### ISSUE TITLE
Add more notification trigger for app

### ISSUE THREAD

**Issue by orgball2608** [orgball2608/webnc-be#123]
## Description
Add more notification trigger for app

## Todos
- [x] When a teacher finalizes a grade composition, create notifications to all students in the class
- [x] When a teacher replies to a student grade review
- [x] When a teacher creates a final decision on a mark review
- [x] Teachers receive a notification when:
- [x] The student requests a grade review
- [x] When a student replies to a teacher grade review

## References
