### ISSUE TITLE
Improve auth strategy

### ISSUE THREAD

**Issue by orgball2608** [orgball2608/webnc-be#131]
## Description
Improve auth strategy

## Todos

- [ ] Remove authenticate middleware
- [ ] Add request context
- [ ] Change role from middleware to guard
- [ ] Fix bug

## References
