### ISSUE TITLE
Implement api for admin page

### ISSUE THREAD

**Issue by orgball2608** [orgball2608/webnc-be#87]
## Description
Implement api for admin page

## Todos

- [x]  Authentication
- [x] Manage user accounts
- [x] Lock/ban an account
- [x] Manually map or unmap the StudentId of an account
- [x] Manage classes
- [x] Add delete student and teacher

## References
